/**
 *
 * $Id$
 */
package fr.ffontenoy.e4.cheatsheet.model.cheatsheets.validation;

import fr.ffontenoy.e4.cheatsheet.model.cheatsheets.Command;

/**
 * A sample validator interface for {@link fr.ffontenoy.e4.cheatsheet.model.cheatsheets.Item}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ItemValidator {
  boolean validate();

  boolean validateTitle(String value);
  boolean validateDescription(String value);
  boolean validateCommand(Command value);
}
